server:
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
    remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 19139
      password: eyJrIjoiYzI3ZmRlZWUzNmVkYjlhZWQyOTdkOTM1NTMzZTJkZWM4OWVkYTNiNyIsIm4iOiJ3aW5kb3dzdGVzdCIsImlkIjo0MzAxMDZ9 
  configs:
    - name: integrations
      scrape_configs:
      - job_name: "windows"
        static_configs:
          - targets: ["localhost:12345"]
        metrics_path: /integrations/windows_exporter/metrics
integrations:
  windows_exporter:
    enabled: true
    enabled_collectors: cpu,cs,logical_disk,net,os,service,system,process
