server:
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
    remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 19139
      password: eyJrIjoiYzI3ZmRlZWUzNmVkYjlhZWQyOTdkOTM1NTMzZTJkZWM4OWVkYTNiNyIsIm4iOiJ3aW5kb3dzdGVzdCIsImlkIjo0MzAxMDZ9 
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true